Repository sds-newbie-longs/longs-backend, pull requests merged in 2023-06, with the labels that each got.

#2 [SL-95] chore: github 관련 파일 추가
  .github/CODEOWNERS
  .github/pull_request_template.md
Labels: enhancement

#4 테스트 application.yml 추가 및 Swagger 설정 profile 분리
  src/main/java/com/sds/actlongs/config/SwaggerConfig.java
  src/test/resources/application.yml
Labels: enhancement

#5 [SL-98] feat: BaseEntity 추가
  src/main/java/com/sds/actlongs/domain/BaseEntity.java
Labels: enhancement

#6 공통 응답 모델 및 예외 핸들러 추가
  longs-formatter.xml
  src/main/java/com/sds/actlongs/advice/GlobalExceptionHandler.java
  src/main/java/com/sds/actlongs/exception/BusinessException.java
  src/main/java/com/sds/actlongs/model/ErrorCode.java
  src/main/java/com/sds/actlongs/model/ErrorResponse.java
  src/main/java/com/sds/actlongs/model/ResultCode.java
  src/main/java/com/sds/actlongs/model/ResultResponse.java
  src/main/java/com/sds/actlongs/util/Constants.java
Labels: enhancement

#9 [SL-101] Group Entity 추가
  src/main/java/com/sds/actlongs/domain/group/entity/Group.java
  src/main/java/com/sds/actlongs/domain/group/repository/GroupRepository.java
  src/test/java/com/sds/actlongs/domain/group/repository/GroupRepositoryTest.java
Labels: enhancement

#11 [SL-103] Board Entity 추가
  longs-formatter.xml
  src/main/java/com/sds/actlongs/domain/board/entity/Board.java
  src/main/java/com/sds/actlongs/domain/board/repository/BoardRepository.java
  src/main/java/com/sds/actlongs/domain/channel/entity/Channel.java
  src/main/java/com/sds/actlongs/domain/channel/repository/ChannelRepository.java
  src/main/java/com/sds/actlongs/domain/group/repository/GroupRepository.java
  src/test/java/com/sds/actlongs/domain/board/repository/BoardRepositoryTest.java
  src/test/java/com/sds/actlongs/domain/channel/repository/ChannelRepositoryTest.java
  src/test/java/com/sds/actlongs/domain/member/repository/MemberRepositoryTest.java
  video/streaming/temp/test.txt
  video/upload/temp/test.txt
Labels: enhancement

#12 CORS 설정 추가
  gradlew.bat
  src/main/java/com/sds/actlongs/config/WebConfig.java
  src/main/java/com/sds/actlongs/util/Constants.java
Labels: enhancement

#13 [SL-104] Video Entity 추가
  src/main/java/com/sds/actlongs/domain/video/entity/Video.java
  src/main/java/com/sds/actlongs/domain/video/respository/VideoRepository.java
  src/main/java/com/sds/actlongs/vo/VideoExtension.java
  src/test/java/com/sds/actlongs/domain/video/respository/VideoRepositoryTest.java
Labels: enhancement

#14 [SL-102] GroupMember Entity 추가
  src/main/java/com/sds/actlongs/domain/channelmember/entity/ChannelMember.java
  src/main/java/com/sds/actlongs/domain/channelmember/repository/ChannelMemberRepository.java
Labels: enhancement

#15 [SL-127] feat: data.sql, schema.sql 추가 및 mysql 버전 8.0 적용(yml)
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/data.sql
  src/main/resources/schema.sql
  src/test/resources/application.yml
Labels: enhancement

#20 Bean Validation 오동작 이슈 해결 및 Swagger docs 업데이트
  src/main/java/com/sds/actlongs/controller/member/MemberController.java
  src/main/java/com/sds/actlongs/controller/member/dto/LoginRequest.java
Labels: enhancement

#26 [SL-157] 메소드 실행 시간 측정 AOP 구현
  src/main/java/com/sds/actlongs/advice/ExecutionTimeAspect.java
  src/main/java/com/sds/actlongs/annotation/MeasureExecutionTime.java
  src/main/java/com/sds/actlongs/util/Constants.java
  src/main/java/com/sds/actlongs/util/TimeUtils.java
  src/test/java/com/sds/actlongs/advice/ExecutionTimeAspectTest.java
  src/test/java/com/sds/actlongs/util/TimeUtilsTest.java
Labels: enhancement

#27 [SL-155] docs: 회원정보 조회 API Swagger 작성
  src/main/java/com/sds/actlongs/controller/member/MemberController.java
  src/main/java/com/sds/actlongs/controller/member/dto/LoginRequest.java
  src/main/java/com/sds/actlongs/controller/member/dto/MemberInfoResponse.java
  src/main/java/com/sds/actlongs/model/ErrorCode.java
  src/main/java/com/sds/actlongs/model/ResultCode.java
Labels: enhancement

#28 [SL-163] docs: 그룹생성 API Swagger 작성
  src/main/java/com/sds/actlongs/controller/channel/ChannelController.java
  src/main/java/com/sds/actlongs/controller/channel/dto/ChannelCreateRequest.java
  src/main/java/com/sds/actlongs/controller/channel/dto/ChannelCreateResponse.java
  src/main/java/com/sds/actlongs/controller/member/MemberController.java
  src/main/java/com/sds/actlongs/model/ResultCode.java
Labels: enhancement

#29 [SL-163] docs: 그룹생성 API Swagger 수정
  src/main/java/com/sds/actlongs/controller/channel/ChannelController.java
  src/main/java/com/sds/actlongs/controller/channel/dto/ChannelCreateRequest.java
  src/main/java/com/sds/actlongs/controller/channel/dto/ChannelCreateResponse.java
Labels: enhancement

#31 [SL-164] docs: 그룹목록 조회 API Swagger 작성
  src/main/java/com/sds/actlongs/controller/channel/ChannelController.java
  src/main/java/com/sds/actlongs/controller/channel/dto/ChannelResponse.java
  src/main/java/com/sds/actlongs/model/ResultCode.java
Labels: enhancement

#32 [NO-ISSUE] 쿠키 관련 설정 추가
  src/main/java/com/sds/actlongs/config/WebConfig.java
Labels: bug

#37 [SL-175] 인증 filter 구현
  src/main/java/com/sds/actlongs/config/SwaggerConfig.java
  src/main/java/com/sds/actlongs/config/WebConfig.java
  src/main/java/com/sds/actlongs/controller/member/MemberController.java
  src/main/java/com/sds/actlongs/filter/AuthenticationFilter.java
  src/main/java/com/sds/actlongs/model/ErrorCode.java
  src/main/java/com/sds/actlongs/util/Constants.java
  src/test/java/com/sds/actlongs/filter/AuthenticationFilterTest.java
Labels: enhancement

#34 [SL-158] docs: 게시글 상세 조회 / 수정 / 삭제 / 검색 API Swagger 작성
  src/main/java/com/sds/actlongs/controller/board/BoardController.java
  src/main/java/com/sds/actlongs/controller/board/SearchController.java
  src/main/java/com/sds/actlongs/controller/board/dto/BoardDeleteResponse.java
  src/main/java/com/sds/actlongs/controller/board/dto/BoardDetailResponse.java
  src/main/java/com/sds/actlongs/controller/board/dto/BoardListResponse.java
  src/main/java/com/sds/actlongs/controller/board/dto/BoardRequest.java
  src/main/java/com/sds/actlongs/controller/board/dto/BoardUpdateRequest.java
  src/main/java/com/sds/actlongs/controller/board/dto/BoardUpdateResponse.java
  src/main/java/com/sds/actlongs/model/ResultCode.java
  src/main/java/com/sds/actlongs/service/board/BoardService.java
  src/main/java/com/sds/actlongs/service/board/BoardServiceImpl.java
Labels: documentation

#42 [NO-ISSUE] fix: dev환경 cors 설정 분리
  src/main/java/com/sds/actlongs/config/WebConfig.java
Labels: bug

#36 [SL-162] docs: 회원 및 그룹 API Swagger 작성
  src/main/java/com/sds/actlongs/controller/channel/ChannelController.java
  src/main/java/com/sds/actlongs/controller/channel/dto/ChannelCreateResponse.java
  src/main/java/com/sds/actlongs/controller/channel/dto/ChannelDeleteResponse.java
  src/main/java/com/sds/actlongs/controller/channel/dto/ChannelListResponse.java
  src/main/java/com/sds/actlongs/controller/channel/dto/ChannelResponse.java
  src/main/java/com/sds/actlongs/controller/channelmember/ChannelMemberController.java
  src/main/java/com/sds/actlongs/controller/channelmember/dto/ChannelLeaveResponse.java
  src/main/java/com/sds/actlongs/controller/channelmember/dto/MemberInviteRequest.java
  src/main/java/com/sds/actlongs/controller/channelmember/dto/MemberInviteResponse.java
  src/main/java/com/sds/actlongs/controller/channelmember/dto/MemberListResponse.java
  src/main/java/com/sds/actlongs/controller/channelmember/dto/MemberSearchResponse.java
  src/main/java/com/sds/actlongs/controller/member/MemberController.java
  src/main/java/com/sds/actlongs/controller/member/dto/LoginResponse.java
  src/main/java/com/sds/actlongs/controller/member/dto/MemberInfoResponse.java
  src/main/java/com/sds/actlongs/model/ResultCode.java
  src/main/java/com/sds/actlongs/model/ResultResponse.java
Labels: documentation

#44 [NO-ISSUE] fix: dev CORS originPatterns wildcard 적용
  src/main/java/com/sds/actlongs/config/WebConfig.java
Labels: bug

#45 [SL-46] 게시글 단건 상세 조회 기능 구현 및 테스트
  src/main/java/com/sds/actlongs/controller/board/BoardController.java
  src/main/java/com/sds/actlongs/controller/board/dto/BoardDetailResponse.java
  src/main/java/com/sds/actlongs/domain/video/repository/VideoRepository.java
  src/main/java/com/sds/actlongs/model/ResultCode.java
  src/main/java/com/sds/actlongs/service/board/BoardService.java
  src/main/java/com/sds/actlongs/service/board/BoardServiceImpl.java
  src/test/java/com/sds/actlongs/service/board/BoardServiceImplTest.java
Labels: enhancement

#39 [SL-174] Ops:Spring Actuator를 올리기 위한 작업
  .github/workflows/ON_SPRINT.yml
  build.gradle
  src/main/java/com/sds/actlongs/config/SwaggerConfig.java
Labels: enhancement

#46 [SL-156] feat: 회원정보 조회API 서비스 구현
  src/main/java/com/sds/actlongs/controller/member/MemberController.java
  src/main/java/com/sds/actlongs/controller/member/dto/MemberInfoResponse.java
  src/main/java/com/sds/actlongs/service/member/MemberService.java
  src/main/java/com/sds/actlongs/service/member/MemberServiceImpl.java
Labels: enhancement

#47 [NO-ISSUE] fix: CORS 에러 해결
  src/main/java/com/sds/actlongs/config/WebConfig.java
  src/main/java/com/sds/actlongs/filter/AuthenticationFilter.java
Labels: bug

#48 [SL-179] feat: 그룹목록 조회 API 서비스 구현
  src/main/java/com/sds/actlongs/controller/channel/ChannelController.java
  src/main/java/com/sds/actlongs/controller/channel/dto/ChannelListResponse.java
  src/main/java/com/sds/actlongs/domain/channel/entity/Channel.java
  src/main/java/com/sds/actlongs/domain/channelmember/repository/ChannelMemberRepository.java
  src/main/java/com/sds/actlongs/domain/member/entity/Member.java
  src/main/java/com/sds/actlongs/filter/AuthenticationFilter.java
  src/main/java/com/sds/actlongs/service/channel/ChannelService.java
  src/main/java/com/sds/actlongs/service/channel/ChannelServiceImpl.java
  src/test/java/com/sds/actlongs/domain/channelmember/repository/ChannelMemberRepositoryTest.java
  src/test/java/com/sds/actlongs/service/channel/ChannelServiceImplTest.java
Labels: enhancement

#49 [NO-ISSUE] Hotfix : swagger / actuator setting
  build.gradle
  src/main/java/com/sds/actlongs/filter/AuthenticationFilter.java
  src/test/java/com/sds/actlongs/ActLongsApplicationTests.java
Labels: enhancement

#50 [SL-45] feat: 게시글 수정 / 삭제 / 메인화면 게시글 목록 조회 기능 추가 및 API 수정
  src/main/java/com/sds/actlongs/controller/board/BoardController.java
  src/main/java/com/sds/actlongs/controller/board/dto/BoardDeleteResponse.java
  src/main/java/com/sds/actlongs/controller/board/dto/BoardRequest.java
  src/main/java/com/sds/actlongs/controller/board/dto/BoardUpdateRequest.java
  src/main/java/com/sds/actlongs/controller/board/dto/BoardUpdateResponse.java
  src/main/java/com/sds/actlongs/controller/channelmember/ChannelMemberController.java
  src/main/java/com/sds/actlongs/domain/board/entity/Board.java
  src/main/java/com/sds/actlongs/domain/channelmember/repository/ChannelMemberRepository.java
  src/main/java/com/sds/actlongs/domain/video/repository/VideoRepository.java
  src/main/java/com/sds/actlongs/exception/BoardNotMatchedMemberException.java
  src/main/java/com/sds/actlongs/model/ErrorCode.java
  src/main/java/com/sds/actlongs/model/ResultCode.java
  src/main/java/com/sds/actlongs/service/board/BoardService.java
  src/main/java/com/sds/actlongs/service/board/BoardServiceImpl.java
  src/main/resources/schema.sql
  src/test/java/com/sds/actlongs/service/board/BoardServiceImplTest.java
Labels: enhancement

#51 [SL-176] feat: 인가 필터 구현
  src/main/java/com/sds/actlongs/controller/board/BoardController.java
  src/main/java/com/sds/actlongs/controller/channel/ChannelController.java
  src/main/java/com/sds/actlongs/controller/member/MemberController.java
  src/main/java/com/sds/actlongs/domain/channelmember/repository/ChannelMemberRepository.java
  src/main/java/com/sds/actlongs/filter/AuthenticationFilter.java
  src/main/java/com/sds/actlongs/filter/AuthorizationFilter.java
  src/main/java/com/sds/actlongs/model/Authentication.java
  src/main/java/com/sds/actlongs/model/ErrorCode.java
  src/main/java/com/sds/actlongs/service/member/MemberServiceImpl.java
  src/main/java/com/sds/actlongs/util/SessionConstants.java
  src/test/java/com/sds/actlongs/filter/AuthenticationFilterTest.java
  src/test/java/com/sds/actlongs/filter/AuthorizationFilterTest.java
  src/test/java/com/sds/actlongs/service/member/MemberServiceImplTest.java
Labels: enhancement

#54 [SL-192] feat: 게시글 제목 검색 API 구현
  src/main/java/com/sds/actlongs/controller/board/BoardController.java
  src/main/java/com/sds/actlongs/controller/board/dto/BoardListSearchResponse.java
  src/main/java/com/sds/actlongs/domain/video/repository/VideoRepository.java
  src/main/java/com/sds/actlongs/service/board/BoardService.java
  src/main/java/com/sds/actlongs/service/board/BoardServiceImpl.java
  src/test/java/com/sds/actlongs/domain/video/repository/VideoRepositoryTest.java
Labels: enhancement

#55 [SL-182] 그룹 생성 API 서비스 구현
  src/main/java/com/sds/actlongs/controller/channel/ChannelController.java
  src/main/java/com/sds/actlongs/controller/channel/dto/ChannelListResponse.java
  src/main/java/com/sds/actlongs/domain/channel/entity/Channel.java
  src/main/java/com/sds/actlongs/domain/channel/repository/ChannelRepository.java
  src/main/java/com/sds/actlongs/service/channel/ChannelService.java
  src/main/java/com/sds/actlongs/service/channel/ChannelServiceImpl.java
  src/main/resources/schema.sql
  src/test/java/com/sds/actlongs/domain/board/repository/BoardRepositoryTest.java
  src/test/java/com/sds/actlongs/domain/channel/repository/ChannelRepositoryTest.java
  src/test/java/com/sds/actlongs/domain/channelmember/repository/ChannelMemberRepositoryTest.java
  src/test/java/com/sds/actlongs/service/channel/ChannelServiceImplTest.java
Labels: enhancement

#56 [SL-187] 그룹원 목록 조회 API 구현
  src/main/java/com/sds/actlongs/controller/channelmember/ChannelMemberController.java
  src/main/java/com/sds/actlongs/controller/channelmember/dto/MemberListResponse.java
  src/main/java/com/sds/actlongs/domain/channelmember/repository/ChannelMemberRepository.java
  src/main/java/com/sds/actlongs/domain/member/entity/Member.java
  src/main/java/com/sds/actlongs/service/channelmember/ChannelMemberService.java
  src/main/java/com/sds/actlongs/service/channelmember/ChannelMemberServiceImpl.java
  src/test/java/com/sds/actlongs/domain/channelmember/repository/ChannelMemberRepositoryTest.java
Labels: enhancement

#61 [SL-195] feat: 그룹 삭제 API 구현
  src/main/java/com/sds/actlongs/controller/channel/ChannelController.java
  src/main/java/com/sds/actlongs/domain/channel/entity/Channel.java
  src/main/java/com/sds/actlongs/domain/channel/repository/ChannelRepository.java
  src/main/java/com/sds/actlongs/domain/channelmember/repository/ChannelMemberRepository.java
  src/main/java/com/sds/actlongs/service/channel/ChannelService.java
  src/main/java/com/sds/actlongs/service/channel/ChannelServiceImpl.java
  src/main/java/com/sds/actlongs/service/channelmember/ChannelMemberServiceImpl.java
  src/main/resources/schema.sql
  src/test/java/com/sds/actlongs/domain/channelmember/repository/ChannelMemberRepositoryTest.java
  src/test/java/com/sds/actlongs/service/channelmember/ChannelMemberServiceImplTest.java
Labels: enhancement

#60 [SL-219] feat: 썸네일 uuid를 url로 변경
  src/main/java/com/sds/actlongs/controller/board/dto/BoardDetailResponse.java
  src/main/java/com/sds/actlongs/controller/board/dto/BoardDto.java
  src/main/java/com/sds/actlongs/util/Constants.java
Labels: enhancement

#62 [NO-ISSUE] feat: 그룹 회원 목록 조회 API 응답 모델 수정
  src/main/java/com/sds/actlongs/controller/channelmember/dto/MemberListResponse.java
Labels: enhancement

#63 [NO-ISSUE] Board column 추가(status) 및 리팩토링
  src/main/java/com/sds/actlongs/domain/board/entity/Board.java
  src/main/java/com/sds/actlongs/domain/board/repository/BoardRepository.java
  src/main/java/com/sds/actlongs/domain/channel/entity/Channel.java
  src/main/java/com/sds/actlongs/domain/video/repository/VideoRepository.java
  src/main/java/com/sds/actlongs/service/board/BoardServiceImpl.java
  src/main/resources/schema.sql
Labels: enhancement

#64 [NO-ISSUE] chore: dummy data 추가 sql 작성
  src/main/resources/data.sql
Labels: enhancement

#66 [NO-ISSUE] Ops : actuator설정
  src/main/resources/application-dev.yml
Labels: enhancement

#57 [SL-193] 회원 검색 API 구현
  src/main/java/com/sds/actlongs/controller/board/dto/BoardDetailResponse.java
  src/main/java/com/sds/actlongs/controller/channelmember/ChannelMemberController.java
  src/main/java/com/sds/actlongs/controller/channelmember/dto/MemberListResponse.java
  src/main/java/com/sds/actlongs/controller/channelmember/dto/MemberSearchResponse.java
  src/main/java/com/sds/actlongs/domain/channelmember/repository/ChannelMemberRepository.java
  src/main/java/com/sds/actlongs/domain/member/entity/Member.java
  src/main/java/com/sds/actlongs/domain/member/repository/MemberRepository.java
  src/main/java/com/sds/actlongs/domain/video/entity/Video.java
  src/main/java/com/sds/actlongs/service/board/BoardServiceImpl.java
  src/main/java/com/sds/actlongs/service/channelmember/ChannelMemberService.java
  src/main/java/com/sds/actlongs/service/channelmember/ChannelMemberServiceImpl.java
  src/main/resources/data.sql
  src/test/java/com/sds/actlongs/domain/video/repository/VideoRepositoryTest.java
  src/test/java/com/sds/actlongs/service/board/BoardServiceImplTest.java
  src/test/java/com/sds/actlongs/service/channelmember/ChannelMemberServiceImplTest.java
Labels: enhancement

#68 [SL-226] 그룹원 초대, 그룹 탈퇴 API 구현
  src/main/java/com/sds/actlongs/controller/channelmember/ChannelMemberController.java
  src/main/java/com/sds/actlongs/controller/channelmember/dto/ChannelLeaveResponse.java
  src/main/java/com/sds/actlongs/controller/channelmember/dto/MemberInviteRequest.java
  src/main/java/com/sds/actlongs/controller/channelmember/dto/MemberInviteResponse.java
  src/main/java/com/sds/actlongs/domain/channelmember/repository/ChannelMemberRepository.java
  src/main/java/com/sds/actlongs/model/ResultCode.java
  src/main/java/com/sds/actlongs/service/channelmember/ChannelMemberService.java
  src/main/java/com/sds/actlongs/service/channelmember/ChannelMemberServiceImpl.java
Labels: enhancement

#69 feature/SL-41
  build.gradle
  src/main/java/com/sds/actlongs/controller/board/BoardController.java
  src/main/java/com/sds/actlongs/controller/board/dto/BoardCreateRequest.java
  src/main/java/com/sds/actlongs/controller/board/dto/BoardCreateResponse.java
  src/main/java/com/sds/actlongs/controller/member/MemberController.java
  src/main/java/com/sds/actlongs/controller/upload/UploadController.java
  src/main/java/com/sds/actlongs/domain/board/entity/Board.java
  src/main/java/com/sds/actlongs/infra/S3Uploader.java
  src/main/java/com/sds/actlongs/model/ResultCode.java
  src/main/java/com/sds/actlongs/service/board/BoardService.java
  src/main/java/com/sds/actlongs/service/board/BoardServiceImpl.java
  src/main/java/com/sds/actlongs/service/convert/FFmpegConvertService.java
  src/main/java/com/sds/actlongs/service/upload/TusUploadService.java
  src/main/java/com/sds/actlongs/util/TimeUtils.java
  src/main/java/com/sds/actlongs/util/duration/DurationExtractor.java
  src/main/java/com/sds/actlongs/util/duration/FFmpegDurationExtractor.java
  src/main/java/com/sds/actlongs/util/manage/file/FileManage.java
  src/main/java/com/sds/actlongs/util/manage/file/FileManageImpl.java
  src/main/java/com/sds/actlongs/util/manage/upload/UploadManage.java
  src/main/java/com/sds/actlongs/util/manage/upload/UploadManageSync.java
  src/main/java/com/sds/actlongs/util/sender/FileSender.java
  src/main/java/com/sds/actlongs/util/sender/FileSenderForS3.java
  src/main/java/com/sds/actlongs/util/thumbnail/FFmpegThumbnailExtractor.java
  src/main/resources/upload.properties
  src/test/java/com/sds/actlongs/ActLongsApplicationTests.java
  src/test/java/com/sds/actlongs/service/convert/FFmpegConvertServiceTest.java
Labels: enhancement

#67 Feature/SL-41
  build.gradle
  src/main/java/com/sds/actlongs/controller/board/BoardController.java
  src/main/java/com/sds/actlongs/controller/board/dto/BoardCreateRequest.java
  src/main/java/com/sds/actlongs/controller/board/dto/BoardCreateResponse.java
  src/main/java/com/sds/actlongs/controller/member/MemberController.java
  src/main/java/com/sds/actlongs/controller/upload/UploadController.java
  src/main/java/com/sds/actlongs/domain/board/entity/Board.java
  src/main/java/com/sds/actlongs/infra/S3Uploader.java
  src/main/java/com/sds/actlongs/model/ResultCode.java
  src/main/java/com/sds/actlongs/service/board/BoardService.java
  src/main/java/com/sds/actlongs/service/board/BoardServiceImpl.java
  src/main/java/com/sds/actlongs/service/convert/FFmpegConvertService.java
  src/main/java/com/sds/actlongs/service/upload/TusUploadService.java
  src/main/java/com/sds/actlongs/util/TimeUtils.java
  src/main/java/com/sds/actlongs/util/duration/DurationExtractor.java
  src/main/java/com/sds/actlongs/util/duration/FFmpegDurationExtractor.java
  src/main/java/com/sds/actlongs/util/manage/file/FileManage.java
  src/main/java/com/sds/actlongs/util/manage/file/FileManageImpl.java
  src/main/java/com/sds/actlongs/util/manage/upload/UploadManage.java
  src/main/java/com/sds/actlongs/util/manage/upload/UploadManageSync.java
  src/main/java/com/sds/actlongs/util/sender/FileSender.java
  src/main/java/com/sds/actlongs/util/sender/FileSenderForS3.java
  src/main/java/com/sds/actlongs/util/thumbnail/FFmpegThumbnailExtractor.java
  src/main/resources/upload.properties
  src/test/java/com/sds/actlongs/ActLongsApplicationTests.java
  src/test/java/com/sds/actlongs/service/convert/FFmpegConvertServiceTest.java
Labels: enhancement

#73 [SL-227] 세션에 저장된 그룹 목록 업데이트
  src/main/java/com/sds/actlongs/controller/channel/ChannelController.java
  src/main/java/com/sds/actlongs/controller/channel/dto/ChannelListResponse.java
  src/main/java/com/sds/actlongs/domain/channel/repository/ChannelRepository.java
  src/main/java/com/sds/actlongs/service/channel/ChannelService.java
  src/main/java/com/sds/actlongs/service/channel/ChannelServiceImpl.java
  src/test/java/com/sds/actlongs/service/channel/ChannelServiceImplTest.java
Labels: enhancement

#76 [SL-234] board 상태값 관련 변경사항
  src/main/java/com/sds/actlongs/controller/board/dto/BoardDetailResponse.java
  src/main/java/com/sds/actlongs/controller/board/dto/BoardDto.java
  src/main/java/com/sds/actlongs/domain/board/entity/Board.java
  src/main/java/com/sds/actlongs/domain/board/repository/BoardRepository.java
  src/main/java/com/sds/actlongs/domain/video/repository/VideoRepository.java
  src/main/java/com/sds/actlongs/service/board/BoardServiceImpl.java
  src/test/java/com/sds/actlongs/domain/board/repository/BoardRepositoryTest.java
  src/test/java/com/sds/actlongs/domain/video/repository/VideoRepositoryTest.java
Labels: enhancement

#80 [SL-243] 회원별 동영상 목록 조회 쿼리문 수정
  src/main/java/com/sds/actlongs/domain/video/repository/VideoRepository.java
  src/main/java/com/sds/actlongs/service/board/BoardServiceImpl.java
  src/main/resources/data.sql
  src/test/java/com/sds/actlongs/service/board/BoardServiceImplTest.java
Labels: bug

#81 [SL-242] fix: ffmpeg 관련 화질 고정 issue 해결 및 로그 코드 추가
  src/main/java/com/sds/actlongs/model/IncodingStatus.java
  src/main/java/com/sds/actlongs/service/convert/ConvertService.java
  src/main/java/com/sds/actlongs/service/convert/FFmpegConvertService.java
  src/main/java/com/sds/actlongs/util/manage/file/FileManage.java
  src/main/java/com/sds/actlongs/util/manage/file/FileManageImpl.java
  src/main/java/com/sds/actlongs/util/manage/upload/UploadManageSync.java
  src/main/resources/upload.properties
Labels: enhancement
